//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022-2023 The Nephio Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package nfdeploy

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BgpConfig) DeepCopyInto(out *BgpConfig) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]BgpInterface, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BgpConfig.
func (in *BgpConfig) DeepCopy() *BgpConfig {
	if in == nil {
		return nil
	}
	out := new(BgpConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BgpInterface) DeepCopyInto(out *BgpInterface) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BgpInterface.
func (in *BgpInterface) DeepCopy() *BgpInterface {
	if in == nil {
		return nil
	}
	out := new(BgpInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Connectivity) DeepCopyInto(out *Connectivity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Connectivity.
func (in *Connectivity) DeepCopy() *Connectivity {
	if in == nil {
		return nil
	}
	out := new(Connectivity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceConfig) DeepCopyInto(out *InterfaceConfig) {
	*out = *in
	if in.IpAddr != nil {
		in, out := &in.IpAddr, &out.IpAddr
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceConfig.
func (in *InterfaceConfig) DeepCopy() *InterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(InterfaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceProfile) DeepCopyInto(out *InterfaceProfile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceProfile.
func (in *InterfaceProfile) DeepCopy() *InterfaceProfile {
	if in == nil {
		return nil
	}
	out := new(InterfaceProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NFCondition) DeepCopyInto(out *NFCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NFCondition.
func (in *NFCondition) DeepCopy() *NFCondition {
	if in == nil {
		return nil
	}
	out := new(NFCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NFDeploy) DeepCopyInto(out *NFDeploy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NFDeploy.
func (in *NFDeploy) DeepCopy() *NFDeploy {
	if in == nil {
		return nil
	}
	out := new(NFDeploy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NFDeployCondition) DeepCopyInto(out *NFDeployCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NFDeployCondition.
func (in *NFDeployCondition) DeepCopy() *NFDeployCondition {
	if in == nil {
		return nil
	}
	out := new(NFDeployCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NFDeploySpec) DeepCopyInto(out *NFDeploySpec) {
	*out = *in
	out.Plmn = in.Plmn
	if in.Sites != nil {
		in, out := &in.Sites, &out.Sites
		*out = make([]Site, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NFDeploySpec.
func (in *NFDeploySpec) DeepCopy() *NFDeploySpec {
	if in == nil {
		return nil
	}
	out := new(NFDeploySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NFDeployStatus) DeepCopyInto(out *NFDeployStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]NFDeployCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NFDeployStatus.
func (in *NFDeployStatus) DeepCopy() *NFDeployStatus {
	if in == nil {
		return nil
	}
	out := new(NFDeployStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Plmn) DeepCopyInto(out *Plmn) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Plmn.
func (in *Plmn) DeepCopy() *Plmn {
	if in == nil {
		return nil
	}
	out := new(Plmn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMFCapacityProfile) DeepCopyInto(out *SMFCapacityProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMFCapacityProfile.
func (in *SMFCapacityProfile) DeepCopy() *SMFCapacityProfile {
	if in == nil {
		return nil
	}
	out := new(SMFCapacityProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMFCapacityProfileSpec) DeepCopyInto(out *SMFCapacityProfileSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMFCapacityProfileSpec.
func (in *SMFCapacityProfileSpec) DeepCopy() *SMFCapacityProfileSpec {
	if in == nil {
		return nil
	}
	out := new(SMFCapacityProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMFType) DeepCopyInto(out *SMFType) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMFType.
func (in *SMFType) DeepCopy() *SMFType {
	if in == nil {
		return nil
	}
	out := new(SMFType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMFTypeSpec) DeepCopyInto(out *SMFTypeSpec) {
	*out = *in
	if in.N4InterfaceProfile != nil {
		in, out := &in.N4InterfaceProfile, &out.N4InterfaceProfile
		*out = make([]InterfaceProfile, len(*in))
		copy(*out, *in)
	}
	if in.N7InterfaceProfile != nil {
		in, out := &in.N7InterfaceProfile, &out.N7InterfaceProfile
		*out = make([]InterfaceProfile, len(*in))
		copy(*out, *in)
	}
	if in.N10InterfaceProfile != nil {
		in, out := &in.N10InterfaceProfile, &out.N10InterfaceProfile
		*out = make([]InterfaceProfile, len(*in))
		copy(*out, *in)
	}
	if in.N11InterfaceProfile != nil {
		in, out := &in.N11InterfaceProfile, &out.N11InterfaceProfile
		*out = make([]InterfaceProfile, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMFTypeSpec.
func (in *SMFTypeSpec) DeepCopy() *SMFTypeSpec {
	if in == nil {
		return nil
	}
	out := new(SMFTypeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Site) DeepCopyInto(out *Site) {
	*out = *in
	if in.Connectivities != nil {
		in, out := &in.Connectivities, &out.Connectivities
		*out = make([]Connectivity, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Site.
func (in *Site) DeepCopy() *Site {
	if in == nil {
		return nil
	}
	out := new(Site)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmfDeploy) DeepCopyInto(out *SmfDeploy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmfDeploy.
func (in *SmfDeploy) DeepCopy() *SmfDeploy {
	if in == nil {
		return nil
	}
	out := new(SmfDeploy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SmfDeploy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmfDeployList) DeepCopyInto(out *SmfDeployList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SmfDeploy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmfDeployList.
func (in *SmfDeployList) DeepCopy() *SmfDeployList {
	if in == nil {
		return nil
	}
	out := new(SmfDeployList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SmfDeployList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmfDeploySpec) DeepCopyInto(out *SmfDeploySpec) {
	*out = *in
	if in.BgpConfigs != nil {
		in, out := &in.BgpConfigs, &out.BgpConfigs
		*out = make([]BgpConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.N4Interfaces != nil {
		in, out := &in.N4Interfaces, &out.N4Interfaces
		*out = make([]InterfaceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.N7Interfaces != nil {
		in, out := &in.N7Interfaces, &out.N7Interfaces
		*out = make([]InterfaceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.N10Interfaces != nil {
		in, out := &in.N10Interfaces, &out.N10Interfaces
		*out = make([]InterfaceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.N11Interfaces != nil {
		in, out := &in.N11Interfaces, &out.N11Interfaces
		*out = make([]InterfaceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VendorRef != nil {
		in, out := &in.VendorRef, &out.VendorRef
		*out = new(ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmfDeploySpec.
func (in *SmfDeploySpec) DeepCopy() *SmfDeploySpec {
	if in == nil {
		return nil
	}
	out := new(SmfDeploySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmfDeployStatus) DeepCopyInto(out *SmfDeployStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]NFCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmfDeployStatus.
func (in *SmfDeployStatus) DeepCopy() *SmfDeployStatus {
	if in == nil {
		return nil
	}
	out := new(SmfDeployStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPFCapacityProfile) DeepCopyInto(out *UPFCapacityProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPFCapacityProfile.
func (in *UPFCapacityProfile) DeepCopy() *UPFCapacityProfile {
	if in == nil {
		return nil
	}
	out := new(UPFCapacityProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPFCapacityProfileSpec) DeepCopyInto(out *UPFCapacityProfileSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPFCapacityProfileSpec.
func (in *UPFCapacityProfileSpec) DeepCopy() *UPFCapacityProfileSpec {
	if in == nil {
		return nil
	}
	out := new(UPFCapacityProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPFType) DeepCopyInto(out *UPFType) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPFType.
func (in *UPFType) DeepCopy() *UPFType {
	if in == nil {
		return nil
	}
	out := new(UPFType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPFTypeSpec) DeepCopyInto(out *UPFTypeSpec) {
	*out = *in
	if in.N3InterfaceProfile != nil {
		in, out := &in.N3InterfaceProfile, &out.N3InterfaceProfile
		*out = make([]InterfaceProfile, len(*in))
		copy(*out, *in)
	}
	if in.N4InterfaceProfile != nil {
		in, out := &in.N4InterfaceProfile, &out.N4InterfaceProfile
		*out = make([]InterfaceProfile, len(*in))
		copy(*out, *in)
	}
	if in.N6InterfaceProfile != nil {
		in, out := &in.N6InterfaceProfile, &out.N6InterfaceProfile
		*out = make([]InterfaceProfile, len(*in))
		copy(*out, *in)
	}
	if in.N9InterfaceProfile != nil {
		in, out := &in.N9InterfaceProfile, &out.N9InterfaceProfile
		*out = make([]InterfaceProfile, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPFTypeSpec.
func (in *UPFTypeSpec) DeepCopy() *UPFTypeSpec {
	if in == nil {
		return nil
	}
	out := new(UPFTypeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpfDeploy) DeepCopyInto(out *UpfDeploy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpfDeploy.
func (in *UpfDeploy) DeepCopy() *UpfDeploy {
	if in == nil {
		return nil
	}
	out := new(UpfDeploy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpfDeploy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpfDeployList) DeepCopyInto(out *UpfDeployList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UpfDeploy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpfDeployList.
func (in *UpfDeployList) DeepCopy() *UpfDeployList {
	if in == nil {
		return nil
	}
	out := new(UpfDeployList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpfDeployList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpfDeploySpec) DeepCopyInto(out *UpfDeploySpec) {
	*out = *in
	if in.BgpConfigs != nil {
		in, out := &in.BgpConfigs, &out.BgpConfigs
		*out = make([]BgpConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.N3Interfaces != nil {
		in, out := &in.N3Interfaces, &out.N3Interfaces
		*out = make([]InterfaceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.N4Interfaces != nil {
		in, out := &in.N4Interfaces, &out.N4Interfaces
		*out = make([]InterfaceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.N6Interfaces != nil {
		in, out := &in.N6Interfaces, &out.N6Interfaces
		*out = make([]InterfaceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.N9Interfaces != nil {
		in, out := &in.N9Interfaces, &out.N9Interfaces
		*out = make([]InterfaceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VendorRef != nil {
		in, out := &in.VendorRef, &out.VendorRef
		*out = new(ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpfDeploySpec.
func (in *UpfDeploySpec) DeepCopy() *UpfDeploySpec {
	if in == nil {
		return nil
	}
	out := new(UpfDeploySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpfDeployStatus) DeepCopyInto(out *UpfDeployStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]NFCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpfDeployStatus.
func (in *UpfDeployStatus) DeepCopy() *UpfDeployStatus {
	if in == nil {
		return nil
	}
	out := new(UpfDeployStatus)
	in.DeepCopyInto(out)
	return out
}
