//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022-2023 The Nephio Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package ausf

import (
	types "github.com/nephio-project/common-lib/nfdeploy"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AusfDeploy) DeepCopyInto(out *AusfDeploy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AusfDeploy.
func (in *AusfDeploy) DeepCopy() *AusfDeploy {
	if in == nil {
		return nil
	}
	out := new(AusfDeploy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AusfDeploy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AusfDeployList) DeepCopyInto(out *AusfDeployList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AusfDeploy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AusfDeployList.
func (in *AusfDeployList) DeepCopy() *AusfDeployList {
	if in == nil {
		return nil
	}
	out := new(AusfDeployList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AusfDeployList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AusfDeploySpec) DeepCopyInto(out *AusfDeploySpec) {
	*out = *in
	out.CapacityProfile = in.CapacityProfile
	out.NfInfo = in.NfInfo
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AusfDeploySpec.
func (in *AusfDeploySpec) DeepCopy() *AusfDeploySpec {
	if in == nil {
		return nil
	}
	out := new(AusfDeploySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AusfDeployStatus) DeepCopyInto(out *AusfDeployStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]types.NFCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AusfDeployStatus.
func (in *AusfDeployStatus) DeepCopy() *AusfDeployStatus {
	if in == nil {
		return nil
	}
	out := new(AusfDeployStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityProfile) DeepCopyInto(out *CapacityProfile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityProfile.
func (in *CapacityProfile) DeepCopy() *CapacityProfile {
	if in == nil {
		return nil
	}
	out := new(CapacityProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NfInfo) DeepCopyInto(out *NfInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NfInfo.
func (in *NfInfo) DeepCopy() *NfInfo {
	if in == nil {
		return nil
	}
	out := new(NfInfo)
	in.DeepCopyInto(out)
	return out
}
